prod1 = input("insira o produto")
prod2 = input("insira o produto")
prod3 = input("insira o produto")

preco1 = float(input("insira um preço do produto"))
preco2 = float(input("insira um preço do produto"))
preco3 = float(input("insira um preço do produto"))

quant1 = int(input("insira a quantidade do produto "))
quant2 = int(input("insira a quantidade do produto "))
quant3 = int(input("insira a quantidade do produto "))
valorTotal1 = preco1*quant1
valorTotal2 = preco2*quant2
valorTotal3 = preco3*quant3
valorArmazem = valorTotal1 + valorTotal2 + valorTotal3

print("valor total",prod1,":", valorTotal1)
print("valor total",prod2,":", valorTotal1)
print("valor total",prod3,":", valorTotal1)







